version: "3.8"

services:
  vaultgallerybot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./gallery.db:/app/gallery.db
      - ./logs:/app/logs
    restart: unless-stopped
